DATASET_FILE = "database/final_data.csv"
DEFAULT_CONFIF_FILE = "config.json"
EMBEDDING_MODEL = "all-MiniLM-L6-v2.gguf2.f16.gguf"
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 0
NO_DOCS_PER_QUERY = 20
MAX_DOCS_TO_LOAD = 100

NUM_COLUMNS = 5